if UnitClassBase("player") ~= "PALADIN" then return end
local addon, ns = ...

Fuyutsui.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "插入物品",
                "战斗时间",
                "移动",
                "施法(正计时)",
                "施法(倒计时)",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "施法技能",
                "施法目标",
            },
            ["特殊"] = {
                "神圣军备",
                "自律",
            },
            ["能量"] = {
                "法力值",
                "神圣能量",
            },
            ["配置开关"] = {
                "爆发开关",
                "延迟",
            },
            ["目标"] = {
                "类型",
                "距离",
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "驱散类型",
                "生命值",

            },
            ["鼠标"] = {
                "类型",
                "驱散类型",
                "生命值",
                "距离",
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["首领1"] = {
                "施法(正计时)",
            },
            ["首领2"] = {
                "施法(正计时)",
            },
        },
        auras = {
            player = {
                { name = "神圣壁垒", spellId = 432502, },
                { name = "圣洁武器", spellId = 432496, },
                { name = "神圣意志", spellId = 223819, },
                { name = "苍穹之遗", spellId = 387178, },
                { name = "圣光灌注", spellId = 54149, maxApps = 2, },
                { name = "晨光", spellId = 431522, maxApps = 3, },
                { name = "晨光-恢复", spellId = 431831, maxApps = 3, },
                { name = "神性之手", spellId = 414273, maxApps = 2, },
                { name = "复仇之怒", spellId = 31884, maxApps = 2, },
                { name = "觉醒", spellId = 414193, },
                { name = "美德道标", spellId = 200025, },
            },
            target = {
                harmful = {
                    { name = "失格者", spellId = 414022, },
                    { name = "奉献", spellId = 204242, },
                },
            },
            focus = {
                harmful = {
                    { name = "失格者", spellId = 414022, },
                    { name = "奉献", spellId = 204242, },
                },
            },
        },
        spells = {
            { spellId = 115750, name = "盲目之光" },
            { spellId = 853, name = "制裁之锤" },
            { spellId = 642, name = "圣盾术" },
            { spellId = 6940, name = "牺牲祝福" },
            { spellId = 1044, name = "自由祝福" },
            { spellId = 1022, name = "保护祝福" },
            { spellId = 633, name = "圣疗术" },
            { spellId = 20473, name = "神圣震击", charge = true, maxCharge = 2 },
            { spellId = 4987, name = "清洁术" },
            { spellId = 275773, name = "审判" },
            { spellId = 375576, name = "圣洁鸣钟" },
            { spellId = 114165, name = "神圣棱镜" },
            { spellId = 31821, name = "光环掌握" },
            { spellId = 200025, name = "美德道标" },
            { spellId = 432459, name = "神圣壁垒", charge = true, maxCharge = 2 },
            { spellId = 391054, name = "代祷" },
        },
        items = {
            [241304] = { name = "治疗药水", isEquipped = false },
        },
        group = {
            num = 6,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            aura = {
                [4] = { name = "圣光道标", spellIds = { 53563, 156910, 1244893 }, },
                [5] = { name = "永恒之火", spellId = 156322, },
            },
        },
    },
    [2] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "插入物品",
                "战斗时间",
                "移动",
                "施法(正计时)",
                "施法(倒计时)",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
            },
            ["特殊"] = {
                "自律",
            },
            ["能量"] = {
                "法力值",
                "神圣能量",
            },
            ["配置开关"] = {
                "延迟",
                "爆发开关",
                "输出模式",
                "AOE开关",
                "爆发药水开关",
            },
            ["目标"] = {
                "类型",
                "距离",
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",

            },
            ["焦点"] = {
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",
                "距离",

            },
            ["鼠标"] = {
                "类型",
                "驱散类型",
                "生命值",
                "距离",
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        auras = {
            player = {
                { name = "闪耀之光", spellId = 327510, maxApps = 2, },
                { name = "小闪耀之光", spellId = 182104, maxApps = 3, },
                { name = "正义盾击", spellId = 132403, },
                { name = "奉献", spellId = 188370, },
                { name = "圣言祭礼", spellId = 433550, },
                { name = "虔诚光环", spellId = 135893, },
            },
        },
        spells = {
            { spellId = 432472, name = "圣洁武器", charge = true, maxCharge = 2 },
            { spellId = 432459, name = "神圣壁垒", charge = true, maxCharge = 2 },
            { spellId = 213644, name = "清毒术" },
            { spellId = 275779, name = "审判", charge = true, maxCharge = 2 },
            { spellId = 31935, name = "复仇者之盾" },
            { spellId = 26573, name = "奉献" },
            { spellId = 53600, name = "正义盾击" },
            { spellId = 85673, name = "荣耀圣令" },
            { spellId = 96231, name = "责难" },
            { spellId = 204019, name = "祝福之锤", charge = true, maxCharge = 3 },
            { spellId = 389539, name = "戒卫" },
            { spellId = 375576, name = "圣洁鸣钟" },
            { spellId = 115750, name = "盲目之光" },
            { spellId = 853, name = "制裁之锤" },
            { spellId = 642, name = "圣盾术" },
            { spellId = 6940, name = "牺牲祝福" },
            { spellId = 1044, name = "自由祝福" },
            { spellId = 1022, name = "保护祝福" },
            { spellId = 633, name = "圣疗术" },
            { spellId = 24275, name = "愤怒之锤" },
        },
        items = {
            [5512] = { name = "治疗石", isEquipped = false },
            [241288] = { name = "鲁莽药水", isEquipped = false },
            [241304] = { name = "治疗药水", isEquipped = false },
            [241308] = { name = "圣光潜力", isEquipped = false },
        },
        group = {
            num = 3,
            healthPercent = 1,
            role = 2,
        },
    },
    [3] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "插入物品",
                "战斗时间",
                "移动",
                "施法(正计时)",
                "施法(倒计时)",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["特殊"] = {
                "自律",
            },
            ["能量"] = {
                "法力值",
                "神圣能量",
            },
            ["配置开关"] = {
                "爆发开关",
                "AOE开关",
                "输出模式",
                "延迟",
            },
            ["目标"] = {
                "类型",
                "距离",
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["鼠标"] = {
                "类型",
                "驱散类型",
                "生命值",
                "距离",
                "施法(倒计时)",
                "施法(正计时)",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        spells = {
            { spellId = 115750, name = "盲目之光" },
            { spellId = 853, name = "制裁之锤" },
            { spellId = 642, name = "圣盾术" },
            { spellId = 6940, name = "牺牲祝福" },
            { spellId = 1044, name = "自由祝福" },
            { spellId = 1022, name = "保护祝福" },
            { spellId = 633, name = "圣疗术" },
            { spellId = 213644, name = "清毒术" },
            { spellId = 20271, name = "审判", charge = true },
            { spellId = 375576, name = "圣洁鸣钟" },
            { spellId = 184575, name = "公正之剑" },
            { spellId = 343527, name = "处决宣判" },
            { spellId = 255937, name = "灰烬觉醒" },
            { spellId = 31884, name = "复仇之怒" },
        },
        items = {
            [241304] = { name = "治疗药水", isEquipped = false },
        },
        group = {
            num = 3,
            healthPercent = 1,
            role = 2,
        },
    },
} -- 创建圣骑士宏{

Fuyutsui.spellsList = {
    -- 圣骑士
    [115750]  = { index = 1, name = "盲目之光" },
    [31821]   = { index = 2, name = "光环掌握" },
    [1044]    = { index = 3, name = "自由祝福" },
    [853]     = { index = 4, name = "制裁之锤" },
    [1022]    = { index = 5, name = "保护祝福" },
    [642]     = { index = 6, name = "圣盾术" },
    [375576]  = { index = 7, name = "圣洁鸣钟" },
    [31935]   = { index = 8, name = "复仇者之盾" },
    [26573]   = { index = 9, name = "奉献" },
    [275779]  = { index = 10, name = "审判" },
    [53600]   = { index = 11, name = "正义盾击" },
    [204019]  = { index = 12, name = "祝福之锤" },
    [184575]  = { index = 13, name = "公正之剑" },
    [20271]   = { index = 14, name = "审判" },
    [383328]  = { index = 15, name = "最终审判" },
    [255937]  = { index = 16, name = "灰烬觉醒" },
    [53385]   = { index = 17, name = "神圣风暴" },
    [427453]  = { index = 18, name = "圣光之锤" },
    [24275]   = { index = 19, name = "愤怒之锤" },
    [343527]  = { index = 20, name = "处决宣判" },
    [1241413] = { index = 21, name = "愤怒之锤" },
    [82326]   = { index = 22, name = "圣光术" },
    [19750]   = { index = 23, name = "圣光闪现" },
    [200025]  = { index = 24, name = "美德道标" },
    [114165]  = { index = 25, name = "神圣棱镜" },
    [53595]   = { index = 26, name = "正义之锤" },
    [6940]    = { index = 27, name = "牺牲祝福" },
    [391054]  = { index = 28, name = "代祷" },
    [633]     = { index = 29, name = "圣疗术" },
    [35395]   = { index = 30, name = "十字军打击" },
    [1241288] = { index = 31, name = "愤怒之锤" },
    [1277026] = { index = 32, name = "愤怒之锤" },
    [1279408] = { index = 33, name = "愤怒之锤" },
    [4987]    = { index = 34, name = "清洁术" },
    [85222]   = { index = 35, name = "黎明之光" },
    -- 种族
    [384255]  = { index = 210, name = "切换天赋" },
    [200749]  = { index = 211, name = "切换专精" },
    [28730]   = { index = 212, name = "奥术洪流" },
    [25046]   = { index = 213, name = "奥术洪流" },
    [50613]   = { index = 214, name = "奥术洪流" },
    [69179]   = { index = 215, name = "奥术洪流" },
    [80483]   = { index = 216, name = "奥术洪流" },
    [129597]  = { index = 217, name = "奥术洪流" },
    [155145]  = { index = 218, name = "奥术洪流" },
    [202719]  = { index = 219, name = "奥术洪流" },
    [232633]  = { index = 220, name = "奥术洪流" },
    [20594]   = { index = 221, name = "石像形态" },
    [58984]   = { index = 222, name = "影遁" },
    [26297]   = { index = 223, name = "狂暴" },
    [20572]   = { index = 224, name = "血性狂怒" },
    [33697]   = { index = 225, name = "血性狂怒" },
    [33702]   = { index = 226, name = "血性狂怒" },
    [20549]   = { index = 227, name = "战争践踏" },
    [59752]   = { index = 228, name = "生存意志" },
    [7744]    = { index = 229, name = "亡灵意志" },
    [20589]   = { index = 230, name = "逃命专家" },
    [68992]   = { index = 231, name = "黑暗飞行" },
    [69070]   = { index = 232, name = "火箭跳" },
    [69041]   = { index = 233, name = "火箭弹幕" },
    [256948]  = { index = 234, name = "空间裂隙" },
    [255647]  = { index = 235, name = "圣光裁决" },
    [274738]  = { index = 236, name = "先祖召唤" },
    [265221]  = { index = 237, name = "烈焰之血" },
    [255654]  = { index = 238, name = "蛮牛冲撞" },
    [255723]  = { index = 239, name = "蛮牛冲撞" },
    [260364]  = { index = 240, name = "奥术脉冲" },
    [312411]  = { index = 241, name = "袋里乾坤" },
    [291944]  = { index = 242, name = "再生" },
    [107079]  = { index = 243, name = "震山掌" },
    [28880]   = { index = 244, name = "纳鲁的赐福" },
    [59542]   = { index = 245, name = "纳鲁的赐福" },
    [59543]   = { index = 246, name = "纳鲁的赐福" },
    [59544]   = { index = 247, name = "纳鲁的赐福" },
    [59545]   = { index = 248, name = "纳鲁的赐福" },
    [59547]   = { index = 249, name = "纳鲁的赐福" },
    [121093]  = { index = 250, name = "纳鲁的赐福" },
    [287712]  = { index = 251, name = "重拳出击" },
    [312924]  = { index = 252, name = "超有机光发起源" },
    [368970]  = { index = 253, name = "扫尾" },
    [357214]  = { index = 254, name = "翼击" },
    [436344]  = { index = 255, name = "艾泽里特涌动" },
}

Fuyutsui.itemsList = {
    [241288] = { index = 1, name = "鲁莽药水" },
    [241289] = { index = 2, name = "鲁莽药水" },
    [241300] = { index = 3, name = "光注法力药水" },
    [241301] = { index = 4, name = "光注法力药水" },
    [241304] = { index = 5, name = "银月城生命药水" },
    [241305] = { index = 6, name = "银月城生命药水" },
    [241308] = { index = 7, name = "圣光潜力" },
    [241309] = { index = 8, name = "圣光潜力" },
    [245897] = { index = 9, name = "飞逝圣光潜力" },
    [245898] = { index = 10, name = "飞逝圣光潜力" },
    [245902] = { index = 11, name = "飞逝鲁莽药水" },
    [245903] = { index = 12, name = "飞逝鲁莽药水" },
    [245916] = { index = 13, name = "飞逝光注法力药水" },
    [245917] = { index = 14, name = "飞逝光注法力药水" },
    [245918] = { index = 15, name = "飞逝银月城生命药水" },
    [245919] = { index = 16, name = "飞逝银月城生命药水" },
    [271883] = { index = 17, name = "浓缩银月城生命药水" },
    [271884] = { index = 18, name = "浓缩银月城生命药水" },
}
